# Generated by Django 3.2.9 on 2022-01-29 14:32

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('accounts', '0002_alter_appuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('expiryTime', models.DateTimeField(default=accounts.models.getExpiryDate)),
            ],
            bases=('authtoken.token',),
        ),
    ]
