# Generated by Django 3.2.9 on 2022-01-03 18:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('currency', models.CharField(choices=[('inr', 'INR'), ('usd', 'USD'), ('eur', 'Euro'), ('pnd', 'Pound')], default='inr', max_length=3)),
                ('category', models.CharField(choices=[('bank', 'banking'), ('book', 'books'), ('clo', 'clothing'), ('edu', 'education'), ('ent', 'entertainment'), ('elec', 'electronics'), ('fash', 'fashion'), ('food', 'food'), ('gift', 'gift'), ('gro', 'grocery'), ('hh', 'household'), ('jew', 'jewelry'), ('misc', 'miscellaneous'), ('med', 'medical'), ('oth', 'other'), ('tra', 'travel')], default='oth', max_length=4)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('receiptImage', models.FileField(blank=True, null=True, upload_to='expense_files')),
                ('transactionType', models.CharField(blank=True, choices=[('cash', 'cash'), ('cc', 'credit card'), ('dc', 'debit card'), ('netb', 'net banking'), ('upi', 'upi')], max_length=4, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('appUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('appUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
                ('expenses', models.ManyToManyField(blank=True, null=True, related_name='collections', to='expense.Expense')),
            ],
        ),
    ]
