# Generated by Django 3.2.9 on 2022-01-08 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(db_index=True, default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='expense',
            name='transactionType',
            field=models.CharField(choices=[('cash', 'cash'), ('cc', 'credit card'), ('dc', 'debit card'), ('netb', 'net banking'), ('upi', 'upi')], default='cash', max_length=4),
        ),
    ]
