# Generated by Django 3.2.9 on 2021-12-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('inr', 'INR'), ('usd', 'USD'), ('eur', 'Euro'), ('pnd', 'Pound')], default='inr', max_length=3),
        ),
    ]
