# Generated by Django 3.2.9 on 2021-12-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_expense_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('bank', 'banking'), ('book', 'books'), ('clo', 'clothing'), ('edu', 'education'), ('ent', 'entertainment'), ('elec', 'electronics'), ('fash', 'fashion'), ('food', 'food'), ('gift', 'gift'), ('gro', 'grocery'), ('hh', 'household'), ('jew', 'jewelry'), ('misc', 'miscellaneous'), ('med', 'medical'), ('oth', 'other'), ('tra', 'travel')], default='oth', max_length=4),
        ),
    ]
